import Head from "next/head";
import { useState } from "react";
import About from "../components/About";
import NavigationHeader from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";

export default function Home() {
  const [popstatus, setPopStatus] = useState<boolean>(false);
  const ChangePopupStatus = () => {
    setPopStatus(!popstatus);
  }

  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll
    scrollbar-thin scrollbar-thumb-gray-400 scrollbar-track-[#292929] overflow-x-hidden z-0 ">
      <Head>
        <title>Abhinav Bhattarai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationHeader ChangePopupStatus={ ChangePopupStatus }/>
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      <section id="experience" className="snap-start">
        <WorkExperience />
      </section>
      <section id='skills' className="snap-start">
        <Skills/>
      </section>
      <section id='projects' className="snap-center">
        <Projects></Projects>
      </section>
      <section id="about" className="snap-end">
        <About />
      </section>
    </div>
  );
}
